const STORE='beango_complete_v1';
const seed={
 outlets:[{id:'o1',name:'BeanGo Central',address:'Kuala Lumpur City Centre',phone:'03-2000 1001',pickup:12,deliveryFee:5,active:true},{id:'o2',name:'BeanGo Damansara',address:'Damansara, Kuala Lumpur',phone:'03-2000 1002',pickup:15,deliveryFee:6,active:true},{id:'o3',name:'BeanGo Putrajaya',address:'Putrajaya',phone:'03-2000 1003',pickup:15,deliveryFee:5,active:true}],
 menu:[{id:'m1',name:'Americano',cat:'Coffee',price:7.9,emoji:'☕',desc:'Espresso + hot water',available:true},{id:'m2',name:'Cafe Latte',cat:'Milk Coffee',price:9.9,emoji:'🥛',desc:'Espresso + fresh milk',available:true},{id:'m3',name:'Cappuccino',cat:'Milk Coffee',price:10.5,emoji:'☕',desc:'Rich foam, balanced espresso',available:true},{id:'m4',name:'Caramel Latte',cat:'Signature',price:11.9,emoji:'🍮',desc:'Caramel + espresso + milk',available:true},{id:'m5',name:'Mocha',cat:'Signature',price:11.5,emoji:'🍫',desc:'Chocolate + espresso + milk',available:true},{id:'m6',name:'Matcha Latte',cat:'Non Coffee',price:12,emoji:'🍵',desc:'Matcha + creamy milk',available:true},{id:'m7',name:'Chocolate',cat:'Non Coffee',price:10,emoji:'🍫',desc:'Rich cocoa drink',available:true},{id:'m8',name:'Spanish Latte',cat:'Signature',price:12.5,emoji:'🥤',desc:'Sweet creamy espresso',available:true}],
 promos:[{id:'p1',code:'WELCOME5',title:'RM5 OFF',type:'fixed',value:5,minSpend:20,active:true},{id:'p2',code:'COFFEE10',title:'10% OFF',type:'percent',value:10,minSpend:25,active:true}],
 users:[],orders:[],session:null,selectedOutlet:'o1'
};
let state=load(),cart=[],category='All',selected=null,opts={size:'Regular',ice:'Normal Ice',sugar:'Normal',addon:'None',qty:1},promo=null,staffTab='orders';
const $=id=>document.getElementById(id),money=n=>'RM'+Number(n||0).toFixed(2),uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function load(){try{const v=JSON.parse(localStorage.getItem(STORE));return v?{...seed,...v}:structuredClone(seed)}catch(e){return structuredClone(seed)}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function activeMenu(){return state.menu.filter(x=>x.available)}
function outlet(){return state.outlets.find(x=>x.id===state.selectedOutlet)||state.outlets[0]}
function renderCats(){const cats=['All',...new Set(activeMenu().map(x=>x.cat))];$('categories').innerHTML=cats.map(c=>`<button class="chip ${c===category?'active':''}" onclick="setCat('${esc(c)}')">${esc(c)}</button>`).join('')}
function setCat(c){category=c;renderCats();renderMenu()}
function renderMenu(){const q=$('searchInput').value.toLowerCase();const items=activeMenu().filter(x=>(category==='All'||x.cat===category)&&x.name.toLowerCase().includes(q));$('menuGrid').innerHTML=items.map(x=>`<article class="menu-card"><div class="drink-art">${x.emoji}</div><div><div class="small">${esc(x.cat)}</div><h4>${esc(x.name)}</h4><div class="small">${esc(x.desc)}</div></div><div class="meta"><span class="price">${money(x.price)}</span><button class="add-btn" onclick="openProduct('${x.id}')">Tambah +</button></div></article>`).join('')||'<p>Tiada menu dijumpai.</p>'}
function openProduct(id){selected=state.menu.find(x=>x.id===id);opts={size:'Regular',ice:'Normal Ice',sugar:'Normal',addon:'None',qty:1};drawProduct();openModal()}
function calcUnit(){return selected.price+(opts.size==='Large'?2:0)+(opts.addon==='Extra Shot'?2:opts.addon==='Oat Milk'?2.5:opts.addon==='Caramel'?1.5:0)}
function drawProduct(){$('modalContent').innerHTML=`<div class="drink-art">${selected.emoji}</div><h2>${esc(selected.name)}</h2><p class="small">${esc(selected.desc)}</p>${group('Saiz',['Regular','Large'],'size')}${group('Ais',['No Ice','Less Ice','Normal Ice'],'ice')}${group('Gula',['No Sugar','Less','Normal'],'sugar')}${group('Add-on',['None','Extra Shot','Oat Milk','Caramel'],'addon')}<div class="qty"><b>Kuantiti</b><button onclick="changeQty(-1)">−</button><strong>${opts.qty}</strong><button onclick="changeQty(1)">+</button></div><button class="primary full" onclick="addToCart()">Tambah ke Cart • ${money(calcUnit()*opts.qty)}</button>`}
function group(title,arr,key){return `<div class="option-group"><h5>${title}</h5><div class="options">${arr.map(v=>`<button class="option ${opts[key]===v?'selected':''}" onclick="pick('${key}','${v}')">${v}</button>`).join('')}</div></div>`}
function pick(k,v){opts[k]=v;drawProduct()}function changeQty(d){opts.qty=Math.max(1,opts.qty+d);drawProduct()}
function addToCart(){cart.push({id:uid('c'),menuId:selected.id,name:selected.name,emoji:selected.emoji,opts:{...opts},unit:calcUnit()});closeModal();updateCart();openCart()}
function subtotal(){return cart.reduce((a,b)=>a+b.unit*b.opts.qty,0)}
function promoDiscount(){if(!promo||subtotal()<promo.minSpend)return 0;return promo.type==='fixed'?Math.min(promo.value,subtotal()):subtotal()*promo.value/100}
function updateCart(){const sub=subtotal(),disc=promoDiscount();$('cartCount').textContent=cart.reduce((a,b)=>a+b.opts.qty,0);$('cartTotal').textContent=money(Math.max(0,sub-disc));$('promoSummary').textContent=promo?`${promo.code}: -${money(disc)}`:'';$('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-item"><div><strong>${x.emoji} ${esc(x.name)} × ${x.opts.qty}</strong><span class="small">${x.opts.size} • ${x.opts.ice} • ${x.opts.sugar}${x.opts.addon!=='None'?' • '+x.opts.addon:''}</span></div><div><b>${money(x.unit*x.opts.qty)}</b><br><button class="close" onclick="removeItem(${i})">×</button></div></div>`).join(''):'<p class="small">Cart masih kosong.</p>'}
function removeItem(i){cart.splice(i,1);updateCart()}function openCart(){$('cartDrawer').classList.remove('hidden')}
function openModal(){$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}
function chooseOutlet(){const items=state.outlets.filter(x=>x.active);$('modalContent').innerHTML=`<h2>Pilih Outlet</h2><div class="order-list">${items.map(x=>`<button class="order-card" onclick="setOutlet('${x.id}')"><strong>${esc(x.name)}</strong><div class="small">${esc(x.address)} • Pickup ±${x.pickup} min</div></button>`).join('')}</div>`;openModal()}
function setOutlet(id){state.selectedOutlet=id;save();renderOutlet();closeModal()}
function renderOutlet(){$('selectedOutletLabel').textContent=outlet().name}
function accountModal(tab='login'){if(state.session?.type==='customer')return renderCustomerAccount();if(state.session?.type==='staff')return showStaff();$('modalContent').innerHTML=`<h2>Account</h2><div class="auth-tabs"><button class="ghost auth-tab" onclick="accountModal('login')">Login</button><button class="ghost auth-tab" onclick="accountModal('register')">Register</button><button class="ghost auth-tab" onclick="accountModal('staff')">Staff</button></div>${tab==='login'?loginForm():tab==='register'?registerForm():staffForm()}`;openModal()}
function loginForm(){return `<form onsubmit="customerLogin(event)"><div class="field"><label>Email</label><input id="aEmail" type="email" required></div><div class="field"><label>Password</label><input id="aPass" type="password" required></div><button class="primary full">Login</button><div id="authMsg" class="notice hidden"></div></form>`}
function registerForm(){return `<form onsubmit="customerRegister(event)"><div class="field"><label>Nama</label><input id="aName" required></div><div class="field"><label>Telefon</label><input id="aPhone" required></div><div class="field"><label>Email</label><input id="aEmail" type="email" required></div><div class="field"><label>Password</label><input id="aPass" type="password" minlength="6" required></div><button class="primary full">Register</button><div id="authMsg" class="notice hidden"></div></form>`}
function staffForm(){return `<form onsubmit="staffLogin(event)"><div class="notice">Demo: admin / CoffeeAdmin@2026 &nbsp;•&nbsp; barista / Barista@2026</div><div class="field"><label>Username</label><input id="staffUser" required></div><div class="field"><label>Password</label><input id="staffPass" type="password" required></div><button class="primary full">Staff Login</button><div id="authMsg" class="notice hidden"></div></form>`}
function msg(t){const e=$('authMsg');if(e){e.textContent=t;e.classList.remove('hidden')}}
function customerRegister(e){e.preventDefault();const email=$('aEmail').value.trim().toLowerCase();if(state.users.some(x=>x.email===email))return msg('Email sudah berdaftar.');const u={id:uid('u'),name:$('aName').value.trim(),phone:$('aPhone').value.trim(),email,password:$('aPass').value};state.users.push(u);state.session={type:'customer',id:u.id};save();closeModal();renderSession();renderCustomerAccount()}
function customerLogin(e){e.preventDefault();const email=$('aEmail').value.trim().toLowerCase(),pass=$('aPass').value;const u=state.users.find(x=>x.email===email&&x.password===pass);if(!u)return msg('Email atau password tidak betul.');state.session={type:'customer',id:u.id};save();closeModal();renderSession()}
function staffLogin(e){e.preventDefault();const u=$('staffUser').value.trim(),p=$('staffPass').value;let role=null;if(u==='admin'&&p==='CoffeeAdmin@2026')role='admin';if(u==='barista'&&p==='Barista@2026')role='barista';if(!role)return msg('Login staff tidak betul.');state.session={type:'staff',role,name:role==='admin'?'Administrator':'Barista Demo'};save();closeModal();showStaff()}
function logout(){state.session=null;save();$('staffView').classList.add('hidden');$('customerView').classList.remove('hidden');renderSession()}
function renderSession(){$('accountBtn').textContent=state.session?.type==='customer'?'👤 '+currentUser().name:state.session?.type==='staff'?'🛠 Staff':'👤 Account'}
function currentUser(){return state.users.find(x=>x.id===state.session?.id)}
function renderCustomerAccount(){const u=currentUser();if(!u)return accountModal();const orders=state.orders.filter(x=>x.userId===u.id).sort((a,b)=>b.createdAt-a.createdAt);$('modalContent').innerHTML=`<h2>${esc(u.name)}</h2><p>${esc(u.email)} • ${esc(u.phone)}</p><button class="danger" onclick="logout();closeModal()">Sign Out</button><hr><h3>Order History</h3>${orders.length?orders.map(orderHtml).join(''):'<p class="small">Belum ada order.</p>'}`;openModal()}
function orderHtml(o){return `<div class="order-card"><div class="order-top"><div><strong>${o.orderNo}</strong><div class="small">${new Date(o.createdAt).toLocaleString('ms-MY')} • ${esc(o.outletName)}</div></div><span class="status-pill">${labelStatus(o.status)}</span></div><p>${o.items.map(i=>`${i.qty}× ${esc(i.name)}`).join(', ')}</p><b>${money(o.total)}</b></div>`}
function checkout(){if(!cart.length)return;if(!state.session||state.session.type!=='customer'){closeCart();return accountModal('login')}const u=currentUser(),o=outlet(),sub=subtotal(),disc=promoDiscount();$('modalContent').innerHTML=`<h2>Checkout</h2><div class="notice">${esc(o.name)} • ${esc(o.address)}</div><form onsubmit="placeOrder(event)"><div class="grid-2"><div class="field"><label>Fulfilment</label><select id="coFulfil"><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select></div><div class="field"><label>Payment</label><select id="coPay"><option value="counter">Pay at Counter</option><option value="online">Online Payment (Demo)</option></select></div></div><div class="field"><label>Nama</label><input id="coName" value="${esc(u.name)}" required></div><div class="field"><label>Telefon</label><input id="coPhone" value="${esc(u.phone)}" required></div><div class="field"><label>Delivery Address (jika delivery)</label><textarea id="coAddress" rows="2"></textarea></div><div class="field"><label>Promo Code</label><div class="top-actions"><input id="coPromo" placeholder="WELCOME5"><button type="button" class="ghost" onclick="applyPromo()">Apply</button></div></div><div class="field"><label>Nota</label><textarea id="coNotes" rows="2" placeholder="Contoh: no straw"></textarea></div><div class="total-row"><span>Subtotal</span><b>${money(sub)}</b></div><div class="total-row"><span>Discount</span><b>-${money(disc)}</b></div><div class="total-row"><span>Delivery fee</span><b id="deliveryFeeText">RM0.00</b></div><div class="total-row"><span>Total</span><b id="checkoutTotal">${money(sub-disc)}</b></div><button class="primary full">Place Order</button></form>`;closeCart();openModal();$('coFulfil').onchange=refreshCheckoutTotal}
function applyPromo(){const code=$('coPromo').value.trim().toUpperCase();const p=state.promos.find(x=>x.active&&x.code===code);if(!p)return alert('Promo tidak sah.');if(subtotal()<p.minSpend)return alert('Minimum spend '+money(p.minSpend));promo=p;updateCart();refreshCheckoutTotal();alert('Promo applied: '+p.title)}
function refreshCheckoutTotal(){const fee=$('coFulfil')?.value==='delivery'?outlet().deliveryFee:0;$('deliveryFeeText').textContent=money(fee);$('checkoutTotal').textContent=money(Math.max(0,subtotal()-promoDiscount()+fee))}
function placeOrder(e){e.preventDefault();const fulfil=$('coFulfil').value,address=$('coAddress').value.trim();if(fulfil==='delivery'&&!address)return alert('Masukkan delivery address.');const fee=fulfil==='delivery'?outlet().deliveryFee:0,sub=subtotal(),disc=promoDiscount(),now=Date.now();const o={id:uid('ord'),orderNo:'BG'+String(now).slice(-7),userId:currentUser().id,outletId:outlet().id,outletName:outlet().name,customerName:$('coName').value.trim(),phone:$('coPhone').value.trim(),fulfil,address,notes:$('coNotes').value.trim(),promoCode:promo?.code||'',subtotal:sub,discount:disc,deliveryFee:fee,total:Math.max(0,sub-disc+fee),paymentMethod:$('coPay').value,paymentStatus:$('coPay').value==='online'?'paid':'pending',status:'new',items:cart.map(x=>({name:x.name,qty:x.opts.qty,unit:x.unit,size:x.opts.size,ice:x.opts.ice,sugar:x.opts.sugar,addon:x.opts.addon})),createdAt:now,updatedAt:now};state.orders.push(o);save();cart=[];promo=null;updateCart();closeModal();showOrder(o)}
function showOrder(o){$('orderStatus').classList.remove('hidden');$('orderStatus').innerHTML=`<h3>✅ Order ${esc(o.orderNo)}</h3><p><b>${labelStatus(o.status)}</b> • ${esc(o.outletName)}</p><p>${o.fulfil==='pickup'?'Pickup anggaran '+outlet().pickup+' min':'Delivery sedang diproses'}</p><p>Payment: <b>${o.paymentStatus==='paid'?'Paid':'Pay at Counter'}</b> • Total <b>${money(o.total)}</b></p>`;$('orderStatus').scrollIntoView({behavior:'smooth'})}
function latestOrder(){const u=state.session?.type==='customer'?currentUser():null;if(!u)return accountModal('login');const o=state.orders.filter(x=>x.userId===u.id).sort((a,b)=>b.createdAt-a.createdAt)[0];if(o)showOrder(o);else alert('Belum ada order.')}
function labelStatus(s){return({new:'New',accepted:'Accepted',preparing:'Preparing ☕',ready:'Ready ✅',out_for_delivery:'Out for Delivery 🛵',completed:'Completed',cancelled:'Cancelled'})[s]||s}
function showHistory(){if(state.session?.type==='customer')renderCustomerAccount();else accountModal('login')}
function showStaff(){if(state.session?.type!=='staff')return accountModal('staff');$('customerView').classList.add('hidden');$('staffView').classList.remove('hidden');$('staffTitle').textContent=state.session.role==='admin'?'Admin Dashboard':'Barista Order Queue';renderStaff()}
function renderStaff(){const active=state.orders.filter(x=>!['completed','cancelled'].includes(x.status));$('staffStats').innerHTML=`<div class="stat"><b>${state.orders.length}</b><span>Total Orders</span></div><div class="stat"><b>${active.length}</b><span>Active</span></div><div class="stat"><b>${state.orders.filter(x=>x.status==='ready').length}</b><span>Ready</span></div><div class="stat"><b>${money(state.orders.reduce((a,b)=>a+(b.status!=='cancelled'?b.total:0),0))}</b><span>Sales</span></div>`;if(staffTab==='orders')renderStaffOrders();if(staffTab==='menu')renderStaffMenu();if(staffTab==='outlets')renderStaffOutlets();if(staffTab==='promos')renderStaffPromos()}
function renderStaffOrders(){const orders=[...state.orders].sort((a,b)=>b.createdAt-a.createdAt);$('staffContent').innerHTML=`<div class="staff-card"><h3>Order Queue</h3><div class="order-list">${orders.length?orders.map(o=>`<div class="queue-card"><div class="order-top"><div><strong>${o.orderNo}</strong><div class="small">${esc(o.customerName)} • ${esc(o.outletName)} • ${o.fulfil}</div></div><span class="status-pill">${labelStatus(o.status)}</span></div><p>${o.items.map(i=>`${i.qty}× ${esc(i.name)} (${i.size}, ${i.ice}, ${i.sugar}${i.addon!=='None'?', '+i.addon:''})`).join('<br>')}</p><div class="top-actions"><b>${money(o.total)}</b>${statusButtons(o)}</div></div>`).join(''):'<p>Belum ada order.</p>'}</div></div>`}
function statusButtons(o){const seq=['new','accepted','preparing','ready',...(o.fulfil==='delivery'?['out_for_delivery']:[]),'completed'];const i=seq.indexOf(o.status);return `${i<seq.length-1?`<button class="mini-btn" onclick="advanceOrder('${o.id}')">→ ${labelStatus(seq[i+1])}</button>`:''}${!['completed','cancelled'].includes(o.status)?`<button class="mini-btn alt" onclick="cancelOrder('${o.id}')">Cancel</button>`:''}`}
function advanceOrder(id){const o=state.orders.find(x=>x.id===id),seq=['new','accepted','preparing','ready',...(o.fulfil==='delivery'?['out_for_delivery']:[]),'completed'];o.status=seq[Math.min(seq.length-1,seq.indexOf(o.status)+1)];o.updatedAt=Date.now();save();renderStaff()}
function cancelOrder(id){const o=state.orders.find(x=>x.id===id);o.status='cancelled';o.updatedAt=Date.now();save();renderStaff()}
function renderStaffMenu(){const admin=state.session.role==='admin';$('staffContent').innerHTML=`<div class="staff-card"><h3>Menu Management</h3>${admin?`<form class="form-row" onsubmit="addMenu(event)"><div class="field"><label>Name</label><input id="mnName" required></div><div class="field"><label>Category</label><input id="mnCat" required></div><div class="field"><label>Price</label><input id="mnPrice" type="number" step=".1" required></div><button class="primary">Add</button></form>`:''}<div class="table-wrap"><table><tr><th>Menu</th><th>Category</th><th>Price</th><th>Status</th><th></th></tr>${state.menu.map(x=>`<tr><td>${x.emoji} ${esc(x.name)}</td><td>${esc(x.cat)}</td><td>${money(x.price)}</td><td>${x.available?'Available':'Off'}</td><td>${admin?`<button class="mini-btn alt" onclick="toggleMenu('${x.id}')">Toggle</button>`:''}</td></tr>`).join('')}</table></div></div>`}
function addMenu(e){e.preventDefault();state.menu.push({id:uid('m'),name:$('mnName').value.trim(),cat:$('mnCat').value.trim(),price:+$('mnPrice').value,emoji:'☕',desc:'New menu item',available:true});save();renderStaffMenu();renderCats();renderMenu()}
function toggleMenu(id){const x=state.menu.find(m=>m.id===id);x.available=!x.available;save();renderStaffMenu();renderCats();renderMenu()}
function renderStaffOutlets(){const admin=state.session.role==='admin';$('staffContent').innerHTML=`<div class="staff-card"><h3>Outlet Management</h3>${admin?`<form class="form-row" onsubmit="addOutlet(event)"><div class="field"><label>Name</label><input id="otName" required></div><div class="field"><label>Pickup min</label><input id="otPickup" type="number" value="15" required></div><div class="field"><label>Delivery Fee</label><input id="otFee" type="number" step=".1" value="5" required></div><button class="primary">Add</button></form>`:''}<div class="order-list">${state.outlets.map(x=>`<div class="order-card"><strong>${esc(x.name)}</strong><div class="small">${esc(x.address)} • Pickup ${x.pickup} min • Delivery ${money(x.deliveryFee)}</div>${admin?`<button class="mini-btn alt" onclick="toggleOutlet('${x.id}')">${x.active?'Disable':'Enable'}</button>`:''}</div>`).join('')}</div></div>`}
function addOutlet(e){e.preventDefault();state.outlets.push({id:uid('o'),name:$('otName').value.trim(),address:'New outlet',phone:'',pickup:+$('otPickup').value,deliveryFee:+$('otFee').value,active:true});save();renderStaffOutlets()}
function toggleOutlet(id){const x=state.outlets.find(o=>o.id===id);x.active=!x.active;save();renderStaffOutlets()}
function renderStaffPromos(){const admin=state.session.role==='admin';$('staffContent').innerHTML=`<div class="staff-card"><h3>Promo / Coupon</h3>${admin?`<form class="form-row" onsubmit="addPromo(event)"><div class="field"><label>Code</label><input id="prCode" required></div><div class="field"><label>Value RM</label><input id="prValue" type="number" step=".1" required></div><div class="field"><label>Min Spend</label><input id="prMin" type="number" step=".1" value="0"></div><button class="primary">Add</button></form>`:''}<div class="order-list">${state.promos.map(x=>`<div class="order-card"><strong>${esc(x.code)} • ${esc(x.title)}</strong><div class="small">Min ${money(x.minSpend)} • ${x.active?'Active':'Disabled'}</div>${admin?`<button class="mini-btn alt" onclick="togglePromo('${x.id}')">Toggle</button>`:''}</div>`).join('')}</div></div>`}
function addPromo(e){e.preventDefault();const val=+$('prValue').value;state.promos.push({id:uid('p'),code:$('prCode').value.trim().toUpperCase(),title:money(val)+' OFF',type:'fixed',value:val,minSpend:+$('prMin').value,active:true});save();renderStaffPromos()}
function togglePromo(id){const x=state.promos.find(p=>p.id===id);x.active=!x.active;save();renderStaffPromos()}
function closeCart(){$('cartDrawer').classList.add('hidden')}
$('searchInput').addEventListener('input',renderMenu);$('cartBtn').onclick=openCart;$('closeCart').onclick=closeCart;$('closeModal').onclick=closeModal;$('checkoutBtn').onclick=checkout;$('changeOutletBtn').onclick=chooseOutlet;$('accountBtn').onclick=()=>accountModal();$('historyBtn').onclick=showHistory;$('trackLatestBtn').onclick=latestOrder;$('staffLogout').onclick=logout;$('staffTabOrders').onclick=()=>{staffTab='orders';renderStaff()};$('staffTabMenu').onclick=()=>{staffTab='menu';renderStaff()};$('staffTabOutlets').onclick=()=>{staffTab='outlets';renderStaff()};$('staffTabPromos').onclick=()=>{staffTab='promos';renderStaff()};renderOutlet();renderCats();renderMenu();updateCart();renderSession();if(state.session?.type==='staff')showStaff();