const menu=[{id:1,name:'Americano',cat:'Coffee',price:7.9,emoji:'☕',desc:'Espresso + hot water'},{id:2,name:'Cafe Latte',cat:'Milk Coffee',price:9.9,emoji:'🥛',desc:'Espresso + fresh milk'},{id:3,name:'Cappuccino',cat:'Milk Coffee',price:10.5,emoji:'☕',desc:'Rich foam, balanced espresso'},{id:4,name:'Caramel Latte',cat:'Signature',price:11.9,emoji:'🍮',desc:'Caramel + espresso + milk'},{id:5,name:'Mocha',cat:'Signature',price:11.5,emoji:'🍫',desc:'Chocolate + espresso + milk'},{id:6,name:'Matcha Latte',cat:'Non Coffee',price:12.0,emoji:'🍵',desc:'Matcha + creamy milk'},{id:7,name:'Chocolate',cat:'Non Coffee',price:10.0,emoji:'🍫',desc:'Rich cocoa drink'},{id:8,name:'Spanish Latte',cat:'Signature',price:12.5,emoji:'🥤',desc:'Sweet creamy espresso'}];
let cart=[];let category='All';let selected=null;let opts={size:'Regular',ice:'Normal Ice',sugar:'Normal',addon:'None',qty:1};
const $=id=>document.getElementById(id);const money=n=>'RM'+n.toFixed(2);
function renderCats(){const cats=['All',...new Set(menu.map(x=>x.cat))];$('categories').innerHTML=cats.map(c=>`<button class="chip ${c===category?'active':''}" onclick="setCat('${c}')">${c}</button>`).join('')}
function setCat(c){category=c;renderCats();renderMenu()}
function renderMenu(){const q=$('searchInput').value.toLowerCase();const items=menu.filter(x=>(category==='All'||x.cat===category)&&x.name.toLowerCase().includes(q));$('menuGrid').innerHTML=items.map(x=>`<article class="menu-card"><div class="drink-art">${x.emoji}</div><div><div class="small">${x.cat}</div><h4>${x.name}</h4><div class="small">${x.desc}</div></div><div class="meta"><span class="price">${money(x.price)}</span><button class="add-btn" onclick="openProduct(${x.id})">Tambah +</button></div></article>`).join('')||'<p>Tiada menu dijumpai.</p>'}
function openProduct(id){selected=menu.find(x=>x.id===id);opts={size:'Regular',ice:'Normal Ice',sugar:'Normal',addon:'None',qty:1};drawModal();$('modal').classList.remove('hidden')}
function drawModal(){const sizeAdd=opts.size==='Large'?2:0,addonAdd=opts.addon==='Extra Shot'?2:opts.addon==='Oat Milk'?2.5:opts.addon==='Caramel'?1.5:0;const total=(selected.price+sizeAdd+addonAdd)*opts.qty;$('modalContent').innerHTML=`<div class="drink-art">${selected.emoji}</div><h2>${selected.name}</h2><p class="small">${selected.desc}</p>${group('Saiz',['Regular','Large'],'size')}${group('Ais',['No Ice','Less Ice','Normal Ice'],'ice')}${group('Gula',['No Sugar','Less','Normal'],'sugar')}${group('Add-on',['None','Extra Shot','Oat Milk','Caramel'],'addon')}<div class="qty"><b>Kuantiti</b><button onclick="changeQty(-1)">−</button><strong>${opts.qty}</strong><button onclick="changeQty(1)">+</button></div><button class="primary full" onclick="addToCart()">Tambah ke Cart • ${money(total)}</button>`}
function group(title,arr,key){return `<div class="option-group"><h5>${title}</h5><div class="options">${arr.map(v=>`<button class="option ${opts[key]===v?'selected':''}" onclick="pick('${key}','${v}')">${v}</button>`).join('')}</div></div>`}
function pick(k,v){opts[k]=v;drawModal()}function changeQty(d){opts.qty=Math.max(1,opts.qty+d);drawModal()}
function addToCart(){const sizeAdd=opts.size==='Large'?2:0,addonAdd=opts.addon==='Extra Shot'?2:opts.addon==='Oat Milk'?2.5:opts.addon==='Caramel'?1.5:0;cart.push({id:crypto.randomUUID?.()||Date.now()+Math.random(),name:selected.name,emoji:selected.emoji,opts:{...opts},unit:selected.price+sizeAdd+addonAdd});$('modal').classList.add('hidden');updateCart();openCart()}
function updateCart(){$('cartCount').textContent=cart.reduce((a,b)=>a+b.opts.qty,0);const total=cart.reduce((a,b)=>a+b.unit*b.opts.qty,0);$('cartTotal').textContent=money(total);$('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-item"><div><strong>${x.emoji} ${x.name} × ${x.opts.qty}</strong><span class="small">${x.opts.size} • ${x.opts.ice} • ${x.opts.sugar}${x.opts.addon!=='None'?' • '+x.opts.addon:''}</span></div><div><b>${money(x.unit*x.opts.qty)}</b><br><button class="close" onclick="removeItem(${i})">×</button></div></div>`).join(''):'<p class="small">Cart masih kosong.</p>'}
function removeItem(i){cart.splice(i,1);updateCart()}function openCart(){$('cartDrawer').classList.remove('hidden')}
function checkout(){if(!cart.length)return;const total=cart.reduce((a,b)=>a+b.unit*b.opts.qty,0);const no='BG'+String(Date.now()).slice(-6);$('cartDrawer').classList.add('hidden');$('orderStatus').classList.remove('hidden');$('orderStatus').innerHTML=`<h3>✅ Order diterima!</h3><p>No. Order <b>${no}</b></p><p>Jumlah: <b>${money(total)}</b></p><p>Status: <b>Preparing ☕</b> — anggaran siap 10–15 minit.</p>`;cart=[];updateCart();$('orderStatus').scrollIntoView({behavior:'smooth'})}
$('searchInput').addEventListener('input',renderMenu);$('cartBtn').onclick=openCart;$('closeCart').onclick=()=>$('cartDrawer').classList.add('hidden');$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('checkoutBtn').onclick=checkout;renderCats();renderMenu();updateCart();